name: Go Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache-dependency-path: "**/go.sum"

      - name: Tools cache
        uses: actions/cache@v4
        env:
          cache-name: go-tools-cache
        with:
          path: .tools
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('./tools/**') }}

      - name: Run lint
        run: make lint

      - name: Build
        run: make build

      - name: Check clean repository
        run: make check-clean-work-tree